### PR TITLE
Pull Request for Issue #11: Support feature navigation voice

### PR DESCRIPTION
**Pull request by puppleStar77**
## Summary
implement Issue #11 "Support feature navigation voice."

## Test
To implement this feature, I have completed testing the following items:
However, I was unable to test the functionality for ATS2.(I don't have ATS2)

- [x] sound level control
- [x] fmod event exit_left
- [x] fmod event exit_now
- [x] fmod event exit_right
- [x] fmod event finish
- [x] fmod event go_straight
- [x] fmod event keep_left
- [x] fmod event keep_right
- [x] fmod event prepare_exit_left
- [x] fmod event prepare_exit_right
- [x] fmod event prepare_turn_left
- [x] fmod event prepare_turn_right
- [x] fmod event recomputing
- [x] fmod event roundabout_1
- [x] fmod event roundabout_2
- [x] fmod event roundabout_3
- [x] fmod event roundabout_4
- [x] fmod event roundabout_5
- [x] fmod event roundabout_6
- [x] fmod event speed_signal
- [x] fmod event speed_warning
- [x] fmod event start
- [x] fmod event turn_left
- [x] fmod event turn_right
- [x] fmod event u_turn
- [x] work for ATS2

## To Reviewers
I kindly request a code review to ensure that the current code adheres to the code conventions. Additionally, I need advice on how to handle warning messages when the navigation voice sound is missing.[(fmod_manager.cpp:152)](https://github.com/puppleStar77/ts-fmod-plugin/blob/39b8b066e59646623f308e7c3e530468e609ed00/ts-fmod-plugin/fmod_manager.cpp#L147-L158)

And what is correct word?
1. gps voice
2. navigation sound
3. navigation voice
4. navigation voice sound
5.  ¯\\_(ツ)_/¯

Finally, I want to say thank you for creating this plugin. Thanks to you, I was able to easily implement the features I wanted.
Thank you in advance for your valuable feedback.

### CODE REVIEW

**Comment by dariowouters** [comment]
That's very nice thank you.
I can confirm that it also works on ATS.
English isn't my native language either, so not sure but "navigation voice" seems the most correct.

As for error handling, if it can't find the event it would be nice if it logged an error if it hasn't errored on that event before. So keep a list of events it has errored on and if it's already in the list don't send an error for that event again. That way it will not spam the console/log.
So if you could add that, that would be great, if not let me know and I'll merge it like it is now and add it myself when I update the plugin for 1.48.

**Comment by puppleStar77** [comment]
If I could provide further explanation about warning handling:
Problem is you can detect if the engine is not loaded by checking "event:/engine/engine" but, for navigation voices, they are not listed under event:/navigation/* but are directly written under the root area of events (e.g., event:/speed_signal, event:/compound_turn_right. Why did you do this, SCS?)

To resolve this, two simple methods come to mind:

1. Check each navigation event individually and display a warning for any events that failed to load.
    like
```c++
    if (fmod_events_map_.find("event:/start") == fmod_events_map_.end())
    {
        scs_log_(SCS_LOG_TYPE_warning,
            "Did not find an 'event:/start' event. You will not have navigation start voice.");
    }
    if (fmod_events_map_.find("event:/finish") == fmod_events_map_.end())
    {
        scs_log_(SCS_LOG_TYPE_warning,
            "Did not find an 'event:/finish' event. You will not have navigation finish voice.");
    }
    if (fmod_events_map_.find("event:/u_turn") == fmod_events_map_.end())
    {
        scs_log_(SCS_LOG_TYPE_warning,
            "Did not find an 'event:/u_turn' event. You will not have navigation start voice.");
    }
```
2.Detect any not loaded navigation events and print warning to console indicating that the currently loaded navigation vocies are incomplete.

Method 1 is the simplest and quickest approach, but the code will be has very long lengthy, and in the worst case (if only one navigation event is used), it might flood the console window with warnings.

Additionally, the navigation voice includes the event "speed_signal." This sound is not a voice but an alert sound. However, 
the most of the sounds are voices, so I think i can call it "navigation voice".

Please let me know if you would like me to follow the current error output format (case 1) or if you prefer to integrate and display the errors together(case 2) If you give me your opinion, I will implement it.
I think case 2 is good.

**Comment by puppleStar77** [comment]
Comment on the newly added sound structure.
I don't know why, navigation_sound_events is an array with only 19 pointers and when I watch it, I can't see all the navigation voices( total voices are 24 ). Maybe there are additional expanded navigation voices, but I don't know exactly where they are connected to, so luckily I found a pointer to the navigation voice that is playing right now( unk_interior+0x0758) , which is normally NULL and then has a pointer to the navigation voice that is playing when the sound is played.

**Comment by dariowouters** [comment]
> Please let me know if you would like me to follow the current error output format (case 1) or if you prefer to integrate and display the errors together(case 2) If you give me your opinion, I will implement it.
I think case 2 is good.

I also think case 2 is the best option.

> I found a pointer to the navigation voice that is playing right now( unk_interior+0x0758) , which is normally NULL and then has a pointer to the navigation voice that is playing when the sound is played.

Yes I saw in the code, it's nice. I like it.

**Comment by puppleStar77** [comment]
Please review the new commits.
I want to integrate the warning log section with the engine, but I couldn't come up with any ideas, so for now, I just simplified it to check and display the navigation only.

**Comment by dariowouters** [comment]
Yes that looks good.
Can I merge this or is there anything you still want to change?

**Pull request merged**
